#!/bin/bash
clear
figlet "SS T PLUS" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.githubusercontent.com/TelksBr/SSH_T_PROJECT_PLUS/main/ssh-plus; chmod 777 ./install; ./install

