#!/bin/bash
echo "obase=16;2^$(nproc)-1" | bc > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo 16384 > /sys/module/nf_conntrack/parameters/hashsize
echo 16384 > /sys/class/net/eth0/queues/rx-0/rps_flow_cnt
echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource
echo never > /sys/kernel/mm/transparent_hugepage/enabled

